name: hr_artugo_app
description: Aplikasi mobile HR internal untuk PT Artugo berbasis Flutter, terintegrasi dengan backend Odoo.
publish_to: 'none' 
version: 1.0.0+1
license: MIT
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # UI & Utilities
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  badges: ^3.1.2
  dotted_border: ^2.1.0
  shimmer: ^3.0.0
  timeago: ^3.7.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1

  # State Management
  get: ^4.6.6

  # Odoo & Network
  odoo_rpc: ^0.7.1
  dio: ^5.4.3+1

  # File & Image Handling
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  flutter_image_compress: ^2.3.0
  cached_network_image: ^3.3.1

  # Device & Permissions
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0

  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Firebase
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.2.1
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.6.0

  # Lainnya (yang sebelumnya hilang)
  flutter_map: ^6.1.0
  flutter_rating_bar: ^4.0.1
  latlong2: ^0.9.0
  faker_dart: ^0.2.2
  google_nav_bar: ^5.0.7
  syncfusion_flutter_charts: ^31.1.19
  timezone: any
  uuid: any
  lottie: ^3.3.1
  mockito: ^5.4.4
  table_calendar: ^3.1.3
  smooth_page_indicator: ^1.2.1
  connectivity_plus: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.3.10
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/animations/
    - assets/images/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ArtuGo.png"
  
  # Konfigurasi khusus untuk Adaptive Icon Android
  adaptive_icon_background: "#FFFFFF" # Warna latar belakang (atau path gambar)
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png" # Path ke logo transparan Anda
flutter_native_splash:
  # Warna latar belakang splash screen. Gunakan kode hex.
  # "#FFFFFF" untuk putih.
  color: "#FFFFFF"

  # Path ke logo utama Anda yang akan ditampilkan di tengah.
  # Pastikan path ini benar dan gambarnya ada.
  image: assets/icon/splash_icon.png

  # Aktifkan untuk platform Android dan iOS
  android: true
  ios: true

  # (Opsional tapi direkomendasikan) Konfigurasi untuk Android 12+
  android_12:
    color: "#FFFFFF"
    image: assets/icon/splash_icon.png
